### ISSUE TITLE
Define winrm windows password

### ISSUE THREAD

**Issue by stephenpearson** [stephenpearson/kitchen-oci#13]
Add a `winrm_password` option to allow the user to override the default randomly generated password.

**Comment by stephenpearson** [comment]
@ehaselwanter I release 1.6.0 which adds the `winrm_password` option so that you can specify a password in the `.kitchen.yml` instead of the random one.  Beware that you'll need to be careful to meet or exceed the password complexity requirements, otherwise the powershell will fail silently and the converge stage will eventually time out and fail.

**Comment by ehaselwanter** [comment]
@stephenpearson great :-) thank you so much!

**Comment by stephenpearson** [comment]
No problem.  I've not seen any issues from anyone, so I'll close this.
