### ISSUE TITLE
Feature Request: Be able to configure IP to use

### ISSUE THREAD

**Issue by ehaselwanter** [stephenpearson/kitchen-oci#2]
Currently it is hardcoded to use the public IP for kitchen to talk to the instance. We need to be able to set this to the private IP

**Comment by stephenpearson** [comment]
Hi @ehaselwanter, I just merged PR #3 which hopefully does what you want.

**Comment by ehaselwanter** [comment]
thx. I'll hopefully can look into it next week as well as report a few other features needed. (auth for proxy, ...)

**Comment by ehaselwanter** [comment]
works as expected (with the fix in #5 )
