### ISSUE TITLE
Support for user_data that is a String

### ISSUE THREAD

**Issue by harlanbarnes** [stephenpearson/kitchen-oci#25]
Hi there - First, thanks for making this, it is a big help to me while getting started with Oracle Cloud.

I want to be able to supply a simple `String` in `user_data` and have it show up in the metadata. I don't think that's currently supported, but I could be wrong. If I am correct and it is not currently supported, I was wondering if you would accept a pull request for this.

That is, if the user data was simply passing a  `String` instead of an `Array` in your standard format then the plugin would write the `user_data` directly to metadata without the mime magic and such. I'll be happy to provide a PR if this is acceptable.

As background, our use case is a we have a generic image that reads what is effectively YAML data from user_data to bootstrap our instances. The data is minimal. And when I do this with `kitchen-ec2` it looks a little funny in `.kitchen.yml` because it's YAML with a string that looks like YAML:

For example:

```
  user_data: |
    env: dev1
    role: tomcat
```

If not, then I'll sort it out some other way. But I thought I would double check.

**Comment by stephenpearson** [comment]
Hello, glad you're finding this project useful!

I've had a quick look at the code, and although I haven't actually tried it I don't think it would work if you supplied a string.  There are method calls that look like they would fail.  Nor can I see a simple way to work around the limitation without a patch.

That said, I do think your use case is both useful and could be integrated without much trouble and cruicially without breaking the existing API.  You're most welcome to submit a PR for it, or if not I may get the chance to cobble something up over the next few days.

**Comment by harlanbarnes** [comment]
I added #26 from what I hacked together for my own use. I tested the original array of hashes and my generic string and both worked fine. One note: I chose not to gzip the String and just base64 encode. This could be wrong. Or at least inconsistent. I'm happy to fix to go either way.

**Comment by stephenpearson** [comment]
It worked in my test environment so I've merged it.  Thanks very much for your PR!  This has been released on rubygems.org as version 1.11.0
