### ISSUE TITLE
Why subnet_id and shape are mandatory parameters when instance_type is dbaas?

### ISSUE THREAD

**Issue by luckeyca** [stephenpearson/kitchen-oci#38]
When creating autonomous database using oci cli and terraform, subnet_id is optional, from oci console, there is not even such option to choose. The "shape" setting doesn't exist when using none of the 3 tools above when creating autonomous database.

**Comment by justintsteele** [comment]
because DBaaS is not the same as autonomous DB.  the driver currently only supports DBaaS
