### ISSUE TITLE
Support for override_attributes in KITCHEN_YAML

### ISSUE THREAD

**Issue by dbaboy** [stephenpearson/kitchen-oci#50]
Reference: Stack**overflow** ([URL](https://stackoverflow.com/questions/78145867/chef-override-attributes-in-kitchen-yaml-default-attributes-vs-chef-env-vs-kitc))

We have a use case where we have an attribute - holding an array of values defined in Cookbook - `attributes/default.rb` file. The attribute is overridden in Chef environment file - this was done under `override_attributes`, this was moved to `default_attributes`. The move was done because we want to be able to override the value in `KITCHEN_YAML`.

```
provisioner:
  name: chef_zero

  #-- Chef environment is read from my-env-repo
  environments_path: ../my-env-repo/environments/
  client_rb:
   environment: my-env
```

We use `kitchen-oci` GEM to provision the Kitcehn VM. Overrides from the Chef environment (_including from the attribute in question_) are used in the Chef recipes.

In `KITCHEN_YAML` file, the override for the attribute is defined under attributes section.

Now, when converging the Kitchen VM, the following is observed.

- If the Chef environment values are defined under `default_attributes` then the actual value becomes additive. That is, the attribute has a value that is combination of array items defined in Cookbook `attributes/default.rb` file and `KITCHEN_YAML` file.

- If the Chef environment values are defined under `override_attributes` then the values in `KITCHEN_YAML` have no effect.

Is above (_from first point_) expected? What would be the ideal way to enable overriding the values in `KITCHEN_YAML` without having to make a copy of the Chef environment and then making adjustment in that.

This issue is created to see if support for `override_attributes` like `node.force_override` can be added to `kitchen-oci` GEM.

**Comment by justintsteele** [comment]
The behavior you are describing is more of a function of test kitchen than of kitchen-oci.  kitchen-oci is merely a driver.  it does not do anything with how the attributes are specified during the chef zero run on the kitchen instance.  if you are struggling with attribute precedence in test kitchen, i would suggest trying to use policyfile rather than berksfile for test kitchen as this will allow you to set attributes in the policyfile as you would normally expect.
