### ISSUE TITLE
honor http proxy/proxy_auth

### ISSUE THREAD

**Issue by ehaselwanter** [stephenpearson/kitchen-oci#7]
according to the oci gem documentation: https://docs.us-phoenix-1.oraclecloud.com/tools/ruby/latest/index.html#label-Proxy+via+the+ApiClientProxySettings+object

the consumer of the gem is responsible to create/pass in an proxy object.
I really would love to just pass in the result of a parsed `HTTP_PROXY=http://<user>:<password>@<address>:<port>` env variable.

do you think it should be an explicit config option in the .kitchen.yml file, or an implicit parsed value from the env variable, if set?

and I'm not so sure about 

```
      return Net::HTTP.new(hostname, port, @proxy_settings.proxy_address) if @proxy_settings.proxy_address.nil?
```

from `oci-2.1.0/lib/oci/api_client.rb:281`

```
    def get_http_object(hostname, port)
      return Net::HTTP.new(hostname, port) if @proxy_settings.nil?
      return Net::HTTP.new(hostname, port, @proxy_settings.proxy_address) if @proxy_settings.proxy_address.nil?

      Net::HTTP.new(
        hostname,
        port,
        @proxy_settings.proxy_address,
        @proxy_settings.proxy_port,
        @proxy_settings.proxy_user,
        @proxy_settings.proxy_password
      )
    end

```

I guess it then should fallback to env parsing?

Shouldn't that read

```
      return Net::HTTP.new(hostname, port, :ENV) if @proxy_settings.proxy_address.nil?
```

or something like that ...

**Comment by ehaselwanter** [comment]
so for now I'm monkey patching it for exactly this case (ignoring non proxy envs) with the following  in my kitchen.yml:

```
<%
require 'oci/api_client'

module OCI
  class ApiClient
  def get_http_object(hostname, port)

       proxy=URI.parse(ENV['http_proxy'])

      Net::HTTP.new(
        hostname,
        port,
        proxy.host,
        proxy.port,
        proxy.user,
        proxy.password
      )
    end
  end
end

%>
```

**Comment by stephenpearson** [comment]
@ehaselwanter I agree, that logic in the get_http_object method does look a bit suspect, but we'll just have to work around it.

I think for our purposes it's entirely sensible to pull the proxy settings from the environment as a fallback.  Generally more specific settings should override less specific settings, so the .kitchen.yml proxy settings (if any exist) should override the environment.

I'll try to add something over the next few days, or do feel free to submit a PR if you end up coding something yourself.

**Comment by ehaselwanter** [comment]
yeah. I guess it should work like in kitchen-ec2. least surprise. for now I'll stick to the patch

**Comment by ehaselwanter** [comment]
can verify that it works with `export http=` as well as kitchen.yml config :-)

**Comment by stephenpearson** [comment]
Great! , I will merge it.  Thank you.

**Comment by ehaselwanter** [comment]
tested updated gem. works. thx :-)
